### ISSUE TITLE
Support golangci-lint

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#215] opened 2019-10-07 16:46 UTC
Add golangci-lint ( https://github.com/golangci/golangci-lint ) to the linters supported by Codacy<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/8151'>Zendesk ticket #8151</a>)<br>gz#8151</i>

**Comment by mrfyda** [comment] 2019-11-08 14:42
Duplicate of #176

**Closed** 2019-11-08 14:42 UTC
Labels: New languages & tools
