### ISSUE TITLE
ESlint delivering not wanted "Prettier: Prettier" issues 

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#384] opened 2020-05-13 16:32 UTC
Pattern "Prettier: Prettier" doesn't seem to be available in user's own config file ".eslintrc.js", although it's delivering issues in the UI , even after re-analysing the whole repository.

Running CLI with the config file ".eslintrc.js" and example file "AddPhoto.js" locally doesn't thrown mentioned issues.

All necessary extra details within zendesk ticket.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10442'>Zendesk ticket #10442</a>)<br>gz#10442</i>

**Comment by lolgab** [comment] 2020-05-19 14:06
The problem depends by the fact that we updated prettier to the latest version (2.0.0) that changed its defaults. The config in the ZenDesk ticket is extending `@react-native-community` that extends [prettier/recommended](https://github.com/facebook/react-native/blob/351a9f10476160eedc44e9d047f8841df12b86d5/packages/eslint-config-react-native-community/index.js#L20). The problem is that `@react-native-community` did not upgrade to prettier 2 yet.
You can:
  - Add prettier to you build so you can use the latest version even locally
  - Add a `prettier` config in your `.eslintrc.js` file to enforce the old defaults

Sadly we can't have both old and new version running in the same tool, so we can't support the same behaviour the outdated `@react-native-community` is having and still have prettier to the latest version as we do.

**Comment by trackwell-mike** [comment] 2020-05-19 15:23
Thanks for that response. Definitely helps. 

We’ll proceed with an update from our end and I’ll confirm status back here.

**Comment by lolgab** [comment] 2020-05-21 15:44
Thank you.
I'm closing the issue since it's not actionable on our side.
Feel free to reopen it if you have any other problems.

**Closed by lolgab** 2020-05-21 15:44 UTC
Labels: Medium Priority, bug
