### ISSUE TITLE
Sonar C# failure when using user's own config file

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#311] opened 2020-03-05 16:20 UTC
When Sonar C# is using user's own configuration file (SonarLint.xml) for the analysis, it's returning the following error message in UI (no problem when running with CLI):

KubernetesDockerRunner: Container for codacy/codacy-sonar-csharp:3.3.0 exited with non-zero code 1
Unhandled Exception:
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0004a] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer+<>c.<GetAnalyzers>b__12_0 (System.Xml.Linq.XElement e) [0x00010] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToArray () [0x0001d] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at System.Collections.Immutable.ImmutableExtensions+FallbackWrapper`1[T].get_Count () [0x00019] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList`1[T].CreateRange (System.Collections.Generic.IEnumerable`1[T] items) [0x00013] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) [0x00013] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList.ToImmutableList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000c] in <2e5af6ef122c4468962237668e6f8259>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer.GetAnalyzers () [0x00056] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer..ctor () [0x00216] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at CodacyCSharp.Analyzer.Program.Main () [0x00000] in <5f10840f939742dfbfd63a6695a0fa72>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Single[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0004a] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer+<>c.<GetAnalyzers>b__12_0 (System.Xml.Linq.XElement e) [0x00010] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].ToArray () [0x0001d] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <7ded87b81a794667956c6beaee0bc32a>:0 
  at System.Collections.Immutable.ImmutableExtensions+FallbackWrapper`1[T].get_Count () [0x00019] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList`1[T].CreateRange (System.Collections.Generic.IEnumerable`1[T] items) [0x00013] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList`1[T].AddRange (System.Collections.Generic.IEnumerable`1[T] items) [0x00013] in <2e5af6ef122c4468962237668e6f8259>:0 
  at System.Collections.Immutable.ImmutableList.ToImmutableList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0000c] in <2e5af6ef122c4468962237668e6f8259>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer.GetAnalyzers () [0x00056] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at CodacyCSharp.Analyzer.CodeAnalyzer..ctor () [0x00216] in <5f10840f939742dfbfd63a6695a0fa72>:0 
  at CodacyCSharp.Analyzer.Program.Main () [0x00000] in <5f10840f939742dfbfd63a6695a0fa72>:0 <br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9533'>Zendesk ticket #9533</a>)<br>gz#9533</i>

**Comment by franciscodua** [comment] 2020-03-09 10:01
It seems like the problem is related to the file being used as configuration.

This tool expects a `SonarLint.xml` xml file with an `AnalysisInput` structure inside. Similar to [this](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/.sonarlint/SonarLint.xml).

Instead, the file has a `RuleSet` structure (like [this one](https://github.com/SonarSource/sonarlint-visualstudio/blob/master/.sonarlint/sonarlint-visualstudioCSharp.ruleset)).

The former is used to configure the tool and the latter to configure the messages shown in the IDE (Visual Studio).

It would be interesting to find out if this was a naming problem, or if there's a use case for this scenario (using Visual Studio's rule sets as configurations).

**Comment by franciscodua** [comment] 2020-03-09 11:53
I'm closing this issue.

Feel free to re-open it you have any other problem or question.

**Comment by mattwaldron** [comment] 2020-03-10 20:28
Hi Francisco,
Thanks for the information.  We were attempting to use the configuration file so that we could view the rule violations in Visual Studio with SonarLint before creating pull-requests to be analyzed by Codacy.  Do you happen to have an XML file for the default Sonar C# settings applied by Codacy?  The AnalysisInput tag appeared to be used for defining custom rules, so it's hard to tell what all in the XML file is required.  There's a lot there for just turning on and off standard rules.
Thanks!
-Matt

**Comment by franciscodua** [comment] 2020-03-11 09:23
Hi @mattwaldron 

If what you want is to configure Sonar C# rules you really need `SonarLint.xml`. If this file exists in your repository, Codacy will use it. If it's not, it does not use any configuration (tool runs with the default configuration), which is equivalent to not having any `SonarLint.xml` on your repository. You can just remove it.

If your goal is to have the same set of rules running on Visual Studio and Codacy, you'll need a `.ruleset` file. Unfortunately, we do not provide a way of syncing your defined rules on Codacy with your rule set.

So my suggestion would be to create your ruleset on Visual Studio and manually sync it with your Codacy patterns. You can follow Microsoft's documentation [here](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-create-a-custom-rule-set?view=vs-2019) and [here](https://docs.microsoft.com/en-us/visualstudio/code-quality/working-in-the-code-analysis-rule-set-editor?view=vs-2019) and change any inactive rule on Codacy to `Action(severity)` = `None`.

Let us know if this helped you.

**Comment by mattwaldron** [comment] 2020-03-11 13:37
Hi @franciscodua,

The need for SonarLint.xml is clear.  The schema is not.  If I understand you correctly, the ruleset format used by the SonarLint plugin for Visual Studio and the format expected by Codacy are incompatible.  Maintaining the rules in two places (manually syncing) like you suggest is not appealing... 

Thanks,
-Matt

**Comment by franciscodua** [comment] 2020-03-11 15:33
Hi @mattwaldron 

Correct, Visual studio's rule sets are not compatible as Sonar C# configurations.

I get your point of maintaining the rules manually synced.
The other alternative is to use [Codacy's CLI](https://github.com/codacy/codacy-analysis-cli) and run the rules locally. However, this is not integrated with Visual Studio. But you can run it before committing or as pre-commit validation.

Would that work for you?

**Comment by mattwaldron** [comment] 2020-03-11 21:30
Hi @franciscodua,

Possibly.  I don't believe anyone in the team is using Docker locally (it's only in the server for build pipeline-related tasks), so introducing that just to run static analysis would be a hurdle.

Thanks!
-Matt

**Closed** 2020-03-12 09:32 UTC
Labels: High Priority
