### ISSUE TITLE
Capitalization issues

### ISSUE THREAD

**Issue by mathieugouin** [codacy/codacy-meta#343] opened 2020-04-06 18:38 UTC
I have a strange issue with capitalization. Example:

```
def moving_average_convergence(x, nslow=26, nfast=12):
First word of the first line should be properly capitalized ('Compute', not 'compute')
    """
    Compute the MACD (Moving Average Convergence/Divergence) using ...
    """
```

Detail:

```
Why is this an issue?
PEP 257 docstring style checker
pep257 is a static analysis tool for checking compliance with Python PEP 257.

The framework for checking docstring style is flexible, and custom checks can be easily added, for example to cover NumPy docstring conventions.

Related code pattern
pep257 tool
pep257 is a static analysis tool for checking compliance with Python PEP 257.
```

**Comment by lolgab** [comment] 2020-04-07 08:33
Hi @mathieugouin,
You can disable individual rules in prospector by adding a `.prospector.yml` file in the root directory of your project. In this particular case you can have a file containing:
```yml
pep257:
  disable:
    - D403
```
To disable the rule that enforces capitalized strings in docstrings.

**Comment by mathieugouin** [comment] 2020-04-08 02:48
Well, I understand that I can disable the rule, but my issue was regarding the fact that my docstring is ALREADY capitalized properly.

Please look again in my example:

```First word of the first line should be properly capitalized ('Compute', not 'compute')```

and my docstring is:
```
    """
    Compute the MACD (Moving Average Convergence/Divergence) using ...
    """
```

I thinks this was closed too early...

**Comment by lolgab** [comment] 2020-04-08 10:28
Sorry for closing the issue too early.
I couldn't reproduce your problem. Prospector seems to behave correctly in respect to capitalized strings.
Added a reproduction here: https://github.com/codacy/codacy-prospector/pull/22
Can you send a reproduction where the tool gives wrong results?

**Comment by mathieugouin** [comment] 2020-04-09 20:22
Ok I found the issue.  It seems that codacy run the script with an outdated version of the code.

This screen shot was taken after the analysis of the following commit: https://github.com/mathieugouin/tradesim/commit/d260c562efeacfb13023f1c650b74652fa7da142

Look at diff, and you will see that the word "This" was removed.  But codacy still thinks it's there, as reported by the report (file is tmxstockquote.py)

![2020-04-09-161820_2720x1024_scrot](https://user-images.githubusercontent.com/11562302/78937131-ec2b9000-7a7d-11ea-84cb-e23e2bba22fa.png)

So I think this is more of a codacy server issue rather than a prospector issue...

**Comment by mathieugouin** [comment] 2020-04-09 20:23
It was a similar issue related to the capitalization issue.  But the root cause seems the same.

**Comment by mrfyda** [comment] 2020-04-17 12:45
@lolgab this issue seems to be caused by the same caching issue we identified on #300, right?

**Comment by lolgab** [comment] 2020-05-28 08:08
Since the caching issue root of this problem is tracked in another issue, I'm closing this.
Thank you.

**Closed by lolgab** 2020-05-28 08:08 UTC
