### ISSUE TITLE
Pylint (Python 3) analyses is failing

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#334] opened 2020-03-25 15:11 UTC
Pylint (Python 3) analyses is failing with below error. This happens with and without user's own config file and seems to be related with the need to have "asttokens==2.0.0":

```
KubernetesDockerRunner: Container for codacy/codacy-pylint-python3:1.3.3 exited with non-zero code 1
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04a44d10d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04a44c8310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04a44c8750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04a44c8c50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f04a4534a10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5a95e7110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5a95de810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5a95dee10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5a95de950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa5a964ba10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f02f4ec37d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f02f4ebaf50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f02f4ebab50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f02f4eba7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f02f4ea4ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1db0ead3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1db0ea8b10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1db0ea8050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1db0ea8f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f1db0ee7890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0f0772a50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0f0769350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0f0769d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0f0769610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0f07d6910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcabaf1cfd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcabaf80650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcabaefdcd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fcabaefd890>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
Traceback (most recent call last):
  File "codacy_pylint.py", line 262, in <module>
    results = runTool('/.codacyrc', '/src')
  File "codacy_pylint.py", line 250, in runTool
    res.extend(runPylintWith(configuration.rules, chunk, srcDir, rcfile_path))
  File "codacy_pylint.py", line 233, in runPylintWith
    cwd)
  File "codacy_pylint.py", line 67, in runPylint
    stdout = process.communicate()[0]
  File "/usr/local/lib/python3.7/subprocess.py", line 951, in communicate
    stdout = self.stdout.read()
TypeError: <lambda>() takes 0 positional arguments but 2 were given


KubernetesDockerRunner: Container for codacy/codacy-pylint-python3:1.3.3 exited with non-zero code 1
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2b1f07d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2b1f61250>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2b1f416d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2b1f6b650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2b1f6b950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90eb0bb9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90eb0f7d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90eb0f7f50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90eb11f450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f90eb11fb10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3554ffa3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3554ff43d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3554ff4ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3554ff4f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f3554ff4d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2234670d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2234ca710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc223447050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc223447d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2234a0f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81b3102610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81b2ffed10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81b2ffebd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81b2ffeb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81b2fe33d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
ERROR: Could not find a version that satisfies the requirement asttokens==2.0.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asttokens==2.0.0 (from -r requirements.txt (line 1))
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa36a023150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa36a0188d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa36a0186d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa36a018e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/asttokens/
Traceback (most recent call last):
  File "codacy_pylint.py", line 262, in <module>
    results = runTool('/.codacyrc', '/src')
  File "codacy_pylint.py", line 250, in runTool
    res.extend(runPylintWith(configuration.rules, chunk, srcDir, rcfile_path))
  File "codacy_pylint.py", line 233, in runPylintWith
    cwd)
  File "codacy_pylint.py", line 67, in runPylint
    stdout = process.communicate()[0]
  File "/usr/local/lib/python3.7/subprocess.py", line 951, in communicate
    stdout = self.stdout.read()
TypeError: <lambda>() takes 0 positional arguments but 2 were given
```
<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9681'>Zendesk ticket #9681</a>)<br>gz#9681</i>

**Comment by lolgab** [comment] 2020-04-03 13:42
The `asttokens` was installed and this should not happen anymore.
I'm closing this issue.
If the problem is still happening feel free to comment.
Lorenzo

**Comment by paulacodacy** [comment] 2020-04-17 12:59
@lolgab This is still happening, please check the zendesk ticket to see the the file where the analysis were done and a file with the error output (same as the one listed in the description here).

**Comment by franciscodua** [comment] 2020-04-21 16:34
Unfortunately, we haven't been able to reproduce this problem on our side. Even using the same configuration file.

To help us better understand the problem:
1. Can you run pylint on your side and tell us if it succeeds and which patterns it finds?
2. You can share your repository with our support team via intercom or email. **Note:** We understand your code is private and if you don't feel comfortable sharing your code feel free to skip this step.

**Comment by paulacodacy** [comment] 2020-05-12 13:58
The zendesk ticket is now updated with the requested information.

**Comment by franciscodua** [comment] 2020-05-14 13:00
Hi

Thanks for providing further information.

According to the logs, it seems that before running this tool, it's trying to download some requirements/dependencies.
In Codacy, we run these tools without internet access, so the requirements will not be downloaded or installed. For this reason, the tool fails, and that's why the error message says it cannot install `asttokens` (it's probably the first dependency it tries to install).

So, for this to work you must ensure you don't need internet access or to install specific dependencies to run Pylint. Start by checking the `init-hook` configuration, which will run arbitrary code before running the tool.

Let us know if this worked for you, or if you have any other question related to this.

**Comment by franciscodua** [comment] 2020-05-19 09:09
I'll close this issue. Feel free to re-open it if the answer did not fit the problem

**Comment by paulacodacy** [comment] 2020-05-27 11:15
Reopening this task, because it seems after "commenting" the line responsible for downloading the dependencies in the config file, same error message is being throw in a newer pull request commit. More details within the zendesk ticket.

**Comment by josemiguelmelo** [comment] 2020-06-02 12:38
Hello,

The first problem you reported is already fixed but it seems you stumbled into a new PyLint problem.

After analysing this new problem, we found out that PyLint is returning a duplicated code false positive on `__init__.py`. This file is empty and makes `git blame` fail. Consequently, the analysis fails.
We opened an issue on PyLint repository (https://github.com/PyCQA/pylint/issues/3661) with the problem mentioned above.

As a workaround, you can temporarily disable the pattern `duplicate-code` by adding it to pylintrc.

**Comment by franciscodua** [comment] 2020-06-08 10:29
Closing this issue.
Re-open it if any question remains, or if the answer was not helpful.

**Closed by franciscodua** 2020-06-08 10:29 UTC
Labels: High Priority, bug
