### ISSUE TITLE
Add support to rubocop-airbnb

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#259] opened 2020-01-24 17:31 UTC
Add support to rubocop-airbnb<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9206'>Zendesk ticket #9206</a>)<br>gz#9206</i>

**Comment by mrfyda** [comment] 2020-01-28 15:05
Duplicate of #258

**Closed by mrfyda** 2020-01-28 15:05 UTC
