### ISSUE TITLE
Wrong UUID being used to upload coverage

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#416] opened 2020-06-15 11:00 UTC
A user is trying to upload coverage using our script on a GitHub action, but the UUID being used doesn't exist on Codacy.

The project is open source and the URL is https://github.com/IagoRegiani/verificador-associacao

The most recent example is UUID a9d2f564118250134b21b65b650b93ecf9249f1c that was used to upload a report but it doesn't exist on the project.<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/10932'>Zendesk ticket #10932</a>)<br>gz#10932</i><br><br><i>(related to <a href='https://codacy.zendesk.com/agent/tickets/10959'>Zendesk ticket #10959</a>)<br>gz#10959</i>

**Comment by franciscodua** [comment] 2020-06-17 16:48
Hi

If you're just looking for a workaround, skip to the workaround section.

# Problem

It seems you found a problem with the coverage reporter when running in Github Actions.

To find the commit UUID, we are leveraging the GITHUB_SHA environment variable (you can see its description [here](https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables)).

However, it seems that Github actions that are triggered on a pull request (meaning: actions that have the `on: pull_request`) give a different value to this environment variable.
According to [this](https://help.github.com/en/actions/reference/events-that-trigger-workflows), the value is the "Last merge commit on the GITHUB_REF branch". Which is better explained in this [issue comment](https://github.com/actions/checkout/issues/27#issuecomment-535897113).

But the idea is, having the `on: pull_request` means the commit that triggered the action is actually a merge commit between your branch and the target branch. But this commit is not part of the pushed tree, so Codacy does not know it.

In the image below you can see an example of the merge commit that gets created (although my commit is `480b8293f4340216b8f630053a230e2867cd5c29`, the environment variable has `bf754c789f905d732f56560ac8357b29263e3077`). These values appear below the `git log`

<img width="923" alt="Screenshot 2020-06-17 at 17 38 33" src="https://user-images.githubusercontent.com/6960449/84925124-60f3f980-b0c1-11ea-9553-7dc73f817e4e.png">

# Workaround

Right now, the best workaround is probably to pass a different value to your commit uuid. This can be done in the call to the command line by adding a `--commit-uuid` flag with your commit UUID in front.

Full example:
Previous:
```bash
bash <(curl -Ls https://coverage.codacy.com/get.sh) report
```
After:
```bash
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --commit-uuid ${{github.event.pull_request.head.sha}}
```

This will work for pull_requests because the ${{github.event.pull_request.head.sha}} will hold the correct commit UUID in these scenarios.

For those using the Github action, the only workaround, for now, is to use the command line as explained above or change the trigger to be `on: push` instead of on pull request.

# Solution
We're still trying to figure out a good way to solve this problem. And we'll get back to you as soon as we have more information

**Comment by franciscodua** [comment] 2020-06-18 13:43
Hi

We just released a fix for this problem codacy/codacy-coverage-reporter/pull/232

Try it out and let us know if it worked for your scenarios.
We appreciate your feedback.

cc. @batespax8 (this might interest you)

We'll close this issue, but if you are still encountering the same problem re-open it and let us know.

**Closed by franciscodua** 2020-06-18 13:43 UTC
Labels: High Priority

**Comment by IagoRegiani** [comment] 2020-06-27 16:52
This fix is also going to be applied to the https://github.com/codacy/codacy-coverage-reporter-action ?

**Comment by franciscodua** [comment] 2020-06-29 07:26
Hi @IagoRegiani 
The Github Action fetches this tool the coverage reporter action tool. So, this fix should also fix the Action. Are you still experiencing problems with it?

**Comment by IagoRegiani** [comment] 2020-07-07 12:19
Yeah, but probably is something on my end. I'll check it out

**Comment by franciscodua** [comment] 2020-07-07 12:59
Hi @IagoRegiani 
If you're having problems with the GitHub action please open an issue on the repository and share some of the information you have, like the error you're experiencing, and ideally a way to reproduce it (we always appreciate that extra help).

We would be happy to help you find the source of the problem
