### ISSUE TITLE
Rubocop generating issues that it shouldn't

### ISSUE THREAD

**Issue by codacy-support** [codacy/codacy-meta#339] opened 2020-03-30 16:52 UTC
We found a case where Rubocop is generating issues that are not reported by our CLI nor are returned locally when the user runs the tool. We have confirmed that the user is using the same version locally that we have on the UI

<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/9738'>Zendesk ticket #9738</a>)<br>gz#9738</i>

**Comment by emeraquino** [comment] 2020-03-30 17:23
Hi guys,

I am not well acquainted with your codebase but my assumption is that the hardcoded plugins [here](https://github.com/codacy/codacy-rubocop/blob/master/src/main/scala/codacy/rubocop/Rubocop.scala#L19) might be always included during the Rubocop checks, thus not respecting the plugins in our configuration file.

Introduced by: https://github.com/codacy/codacy-rubocop/pull/62

Best,

**Comment by josemiguelmelo** [comment] 2020-03-31 07:47
Hi @emeraquino 

Many thanks for reporting this bug  🙏
The bug is indeed related with that plugins list. We were passing that list of plugins to rubocop as `--required`. Due to that, those plugins were always required even if not present on the configuration file provided.

This bug should be fixed by this PR: https://github.com/codacy/codacy-rubocop/pull/76
I'll let you know when we push this fix to production 😊

Best,

**Comment by josemiguelmelo** [comment] 2020-04-03 09:51
Hi @emeraquino 

The fix is now in production. Can you confirm if the problem is solved? 😊

Thanks,
José

**Closed** 2020-04-07 16:01 UTC
Labels: High Priority, bug
