### ISSUE TITLE
Checkstyle 8.23 does not report any issue if some patterns are enabled.

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-meta#213] opened 2019-10-03 17:01 UTC
We detected that if some patterns are enabled Checkstyle will end is success but no patterns will be returned regardless of the pattern that should be triggered.

The patterns we found with this behavior are:

JavaDoc*****
Translation
IllegalImport<br><br><i>(created from <a href='https://codacy.zendesk.com/agent/tickets/8125'>Zendesk ticket #8125</a>)<br>gz#8125</i>

**Comment by mrfyda** [comment] 2019-10-07 14:53
This is a duplicate of https://github.com/codacy/codacy-checkstyle/issues/43

**Closed by mrfyda** 2019-10-07 14:53 UTC
